---
title: "MobileTelcoSegmentation"
author: "Francisco Roque"
date: "27 de janeiro de 2017"
output: html_document
---
<<<<<<< HEAD

#Telecom Buisness e
<br>
We are studying a database providing telecommunication consumption data.
The company is providing services in Ghana, and our focus will be exclusively on customers who buy prepaid packages (same as Starhub prepaid packages)

##Objectives of the project : Understand Customers consumptions habit in order for the company to offer the right packages to the right customer segment.


###1)	The business questions :

What are our customer segment based on historical data/voice usage? And how shall we serve them better with our services?
Our Goal : define the customer segment and characterize them with their service usage.

=======
fff
1)	The business questions
blablablblblbalblablbalbzkjdabkd
>>>>>>> 5528cf4e581e50936547b0eda3517be27d3cf85d

###2)	The process
a.	List and description of steps below)

dasakdjhsajdhsajdhsd
akdsjhsjadh

###3)	The data
a.	Load the data



b.	Describe the data (highlevel description of contents, # of rows, # of columns, list the columns and its meaning, show a sample of the data)



###4)	PART 1: Factor/Component selection

a.	Step 1: Descriptive statistics of the data



b.	Step 2: Some visual charts of the data that are useful to understand the data (e.g. histogram of gigabytes used per client)




c.	Step 3: Check correlations (this is another step to just get to know better the data)



d.	Step 4: Choose method to select number of factors/components

i.	This part will imply going through several iterations of playing with the methods and discussing the results until it all makes sense




e.	Step 5: Name and describe the final selected factors/components




f.	Step 6: Consolidate all the data into only the factors/components




###5)	PART 2: Segmentation

a.	Step 1: Visualize the pair-wise distances and decide distance metric to define how different customers must be to be considered different




b.	Step 2: Segmentation and Robustness Analysis

i.	Segmentation - Play around with the different segmentation methods until we get a result that makes sense
<br>
<br>
<br>
<br>
<br>
ii.	Robustness Analysis - Show the different method used, its results and why it didn’t make sense






c.	Step 3: Profile and interpret the above defines segments
i.	This is the final output
